const GET_MOVIES = "GET_MOVIES";
const GET_GENRES = "GET_GENRES";
const IS_GENRES_LOADED = "IS_GENRES_LOADED";
const IS_MOVIES_LOADED = "IS_MOVIES_LOADED";

export { GET_MOVIES, GET_GENRES, IS_MOVIES_LOADED, IS_GENRES_LOADED };
